DROP TABLE IF EXISTS payment CASCADE;
DROP TABLE IF EXISTS booking CASCADE;
DROP TABLE IF EXISTS room CASCADE;
DROP TABLE IF EXISTS admin CASCADE;
DROP TABLE IF EXISTS member CASCADE;
DROP TABLE IF EXISTS account CASCADE;
